### ISSUE TITLE
jamfcpr doesn't work with Jamf Pro 10.27.0

### ISSUE THREAD

**Issue by entusdictus** [BIG-RAT/jamfcpr#1]
I've tested this against a few JPS with 10.27.0 installed and the tool doesn't list any packages. Of course account credentials are correct and working. I've tested using full admin accounts. Reproducible for any JPS with 10.27.0.

<img width="372" alt="Error message" src="https://user-images.githubusercontent.com/14052665/108030676-e9031800-702f-11eb-89e9-21b4a6f9df68.png">

**Comment by BIG-RAT** [comment]
Thanks for the note.  Noticed over the weekend the authentication I was using (in several apps) no longer works starting with 10.27.  This one should be fixed now, v0.9.7.

**Comment by entusdictus** [comment]
Works, thanks :)
