### ISSUE TITLE
'Verify All Destinations Are Filled' error when only trying to save locally

### ISSUE THREAD

**Issue by ParanoidAndroid91** [BIG-RAT/jamfcpr#11]
As above. I cannot download PKGs from any Jamf Cloud instances, I just receive the above error even when everything is configured correctly.

**Comment by ParanoidAndroid91** [comment]
So it turns out I now have to enter my local computer account credentials and specify a destination - I never had to do this before, everything just went to Downloads automatically.

Also, it just spins the little circle logo and doesn't let me actually download any of the visible PKGs.

**Comment by BIG-RAT** [comment]
Thanks for the heads up.  If you put the same info in both source and destination are you able to download.  I'll look to fix things so that destination info is not needed when save only is selected.

**Comment by ParanoidAndroid91** [comment]
That does indeed work, thanks 😊 However, it still says 'Upload completed' as though it's tried to send it to the same JSS again.

**Comment by BIG-RAT** [comment]
Issue should be addressed in latest version, v3.3.3.

**Comment by ParanoidAndroid91** [comment]
> Issue should be addressed in latest version, v3.3.3.

Wicked, thanks mate I’ll give it a try tomorrow.

**Comment by ParanoidAndroid91** [comment]
@BIG-RAT - Sorted, absolute diamond!

**Comment by BIG-RAT** [comment]
Thanks for the update.
