### ISSUE TITLE
Crashes in SaveA

### ISSUE THREAD

**Issue by rs1278** [BIG-RAT/jamfcpr#13]
jamfcpr crashes when running in Save Only mode

I am running an M1 MacbookPro and are running a JAMF cloud instance with SSO enabled. Our SSO uses PIV smart card authentication, however, I have tried using a non-SSO enabled local JAMF account and the behavior continues. I have also tried using https://<site>.jamfcloud/?failover to see if anything changes, but this also did not work.

**Comment by BIG-RAT** [comment]
Works fine migrating packages to another server?  Lists packages work in save only mode?  If you're able to share the log file (~/Library/Logs/jamfcpr/*****jamfcpr.log) that may help track down the issue.

**Comment by rs1278** [comment]
[20221107_091910_jamfcpr copy.log](https://github.com/BIG-RAT/jamfcpr/files/9953514/20221107_091910_jamfcpr.copy.log)


Thanks for the response, here is the log file. I have redacted part of our jamf cloud URL for privacy reasons.

this is the full log after jamfcpr crashes

**Comment by rs1278** [comment]
curious if there is any insight after peaking at the logs?

**Comment by BIG-RAT** [comment]
I'm still stumped.  Curious what login window is displayed (SSO of standard Jamf Pro) when you hit https://<redacted>.jamfcloud.com/packages.html
Might try the url in a private window to ensure existing credentials aren't passed.
I should also ask if you're able to login with the credentials you're using in jamfcpr, and see the packages.
Again, is it just an issue with save only mode, does migrating from one server to another work?

**Comment by rs1278** [comment]
<img width="2558" alt="Screenshot 2022-12-14 at 9 35 46 AM" src="https://user-images.githubusercontent.com/92549755/207654432-f252351f-bc8e-47d2-8343-d8d4801143de.png">
This is where I land...Its asking for our smart card authentication. If I click cancel, I can proceed to our smart card SSO failover screen for username/password authentication.

Could there maybe be a way to leverage the API within jamfCPR as a workaround here?

**Comment by BIG-RAT** [comment]
Thanks for the speedy reply.  Actually working to get rid of the call to packages.html and use the API to check access rights.

**Comment by rs1278** [comment]
Awesome! Hopefully, API calls will resolve this.

To answer your other questions, I've only tried save mode, as I don't have a need for server migration and I don't see any packages in jamfcpr.

**Comment by BIG-RAT** [comment]
Just occurred to me,  `https://your.jamfcloud.com/legacy/packages.html?id=-1&o=c` is also queried, but only for copying packages to the destination server so Save Only should work.  Information obtained there can't be gathered from the API.

**Comment by BIG-RAT** [comment]
Authentication changed.  As time permits let me know if the issue is resolved in v3.5.0.

**Comment by rs1278** [comment]
This fixed the issue. Thanks!!
