### ISSUE TITLE
Update to Client ID/Secret

### ISSUE THREAD

**Issue by sbryant82** [BIG-RAT/jamfcpr#15]
Can you please update the app to support Jamf's migration of APIs to the Client ID and Client Secret?

**Comment by BIG-RAT** [comment]
Will be included in the next version, for JCDS2.

**Comment by sbryant82** [comment]
Do you have an anticipated release date for this?

**Comment by BIG-RAT** [comment]
Looking to get a beta out before next week.

**Comment by sbryant82** [comment]
Thank you, It's much appreciated.

**Comment by BIG-RAT** [comment]
In case you didn't see it: 
Wiki - [Beta](https://github.com/BIG-RAT/jamfcpr/wiki)
