### ISSUE TITLE
Missing info in the history of a package uploaded using jamfCPR

### ISSUE THREAD

**Issue by sbryant82** [BIG-RAT/jamfcpr#16]
Looks like "Add information" (when it was uploaded, the account used to upload, and that is was uploaded with jamfCPR) to the Notes section for a package in Jamf Pro is not happening in beta 5
![History](https://github.com/BIG-RAT/jamfcpr/assets/126191345/88d87440-b635-4497-9437-6ed1aad97c62)

Only showing the username as the API client ID. no note that it was uploaded by jamfCPR.

**Comment by BIG-RAT** [comment]
Certainly won’t show up in the history, should see it back on the General tab of a package.  Notes is just below the Info box.  Let me know if it’s not there.

**Comment by sbryant82** [comment]
Sorry about that. It was in the Notes area. 
![Notes](https://github.com/BIG-RAT/jamfcpr/assets/126191345/f85f3c7d-9728-4368-8cc8-c1ba950eb18b)


It only shows the long Client ID as to who it was added by. Any way to add a field to indicate who is using the tool?

**Comment by BIG-RAT** [comment]
That's a good idea (grab the logged in user on the machine) since the API client may be shared among support staff.

**Comment by BIG-RAT** [comment]
Added additional info.
