### ISSUE TITLE
Using the API Client, not able to pull in full database

### ISSUE THREAD

**Issue by sbryant82** [BIG-RAT/jamfcpr#18]
After doing some extensive testing, with a server with a username/password, I was able to pull in the full server.
Using the API Client/secret, it only pulls in items from the database starting with S's through Z's.

**Comment by BIG-RAT** [comment]
v4.1.0 address some API client issues.  See if it helps with this one.

**Comment by sbryant82** [comment]
Testing today , appears that it is now pulling in the rest of the database now. seeing a-z items now.

Thanks for the update.
