### ISSUE TITLE
Unable to retrieve data from the JCDS XX Status Code 500 on v4.0.2

### ISSUE THREAD

**Issue by markkenny** [BIG-RAT/jamfcpr#19]
Hi, I thought it was our AWS S3 storage not working with jamfcpr, but my colleague showed it working, and I replicated on v3.3.4.

Unable to retrieve data from the JCDS on https://MINE/.
Status code: 500

Not using API Client, same API user and creds in both versions. 

Thanks

**Comment by BIG-RAT** [comment]
Status code: 500 typically indicates Jamf Pro is utilizing JCDS1.  Jamf CPR v3.x is for JCDS1 only and Jamf CPR 4.x is JCDS2 only.

**Comment by markkenny** [comment]
Gotcha. So working as intended ;-) Thank you
