### ISSUE TITLE
strange values in the log (incomplete logging?)

### ISSUE THREAD

**Issue by randomName0815** [BIG-RAT/jamfcpr#20]
Hi, my package list is empty at one instance, but they are read out in the logged json.
Can't find any error/failure in the logs, but there are many apparently cropped lines, such as these (marked bold):

> 20240205_151625 [endPointByID] endpoint passed to endPointByID: packages/id/179
> **XYZ.jamfcloud.com**
> 20240205_151625 [ApiAction.getPackages] looking up: DNGConverter_15_4.pkg
> **.com/JSSResource/packages/id/179**
> **h/token)**
> 20240205_151625 [JamfPro.getToken] Generate token for source server: https://XYZ.jamfcloud.com
> 20240205_151625 [JamfPro.getToken] Use existing token from Optional(https://XYZ.jamfcloud.com/api/v1/auth/token)
> 20240205_151626 [JamfPro.getToken] Generate token for source server: https://XYZ.jamfcloud.com
> 20240205_151626 [JamfPro.getToken] Use existing token from Optional(https://XYZ.jamfcloud.com/api/v1/auth/token)
> 20240205_151626 [JamfPro.getToken] Generate token for source server: https://XYZ.jamfcloud.com
> 20240205_151626 [endPointByID] fetching XML from: https://XYZ.jamfcloud.com/JSSResource/packages/id/178
> **h/token)**
> 20240205_151626 [endPointByID] endpoint passed to endPointByID: packages/id/185
> **XYZ.jamfcloud.com**

I see the behavior on a 11.1.1 sandbox, on another 11.2.0 it works normally, but also with the strange log outputs.
I wanted to open an issue about the empty package list, but I think the logging would have to be fixed first.

tested with jamfcpr 4.0.2 
Two Jamf Pro Sandbox Cloud Instances on 11.1.1 & 11.2.0 
with User+PW and API Client

best regards and thx for your great work !

**Comment by BIG-RAT** [comment]
v4.1.1 has been posted. Please re-open the issue if the behavior persists.
