### ISSUE TITLE
Issues with Light mode

### ISSUE THREAD

**Issue by entusdictus** [BIG-RAT/jamfcpr#3]
When using jamfcpr in Light system appearance, the package list is not displayed correctly.
Seems as if the text color is hardcoded to white instead of using system appearance. 

<img width="934" alt="Package list" src="https://user-images.githubusercontent.com/14052665/114991172-990ec900-9e99-11eb-9547-5ab04c39056c.png">

<img width="934" alt="selection" src="https://user-images.githubusercontent.com/14052665/114991181-9b712300-9e99-11eb-98f5-33b44e8c4056.png">

**Comment by BIG-RAT** [comment]
Should be resolved with v1.0.2 - thanks for details.
