### ISSUE TITLE
Unable to retrieve upload information for destination server

### ISSUE THREAD

**Issue by pete-c-jll** [BIG-RAT/jamfcpr#6]
jamfcpr 2.0.0. returns "Unable to retrieve upload information for destination server" regardless of options set uploading from local SMB:8443 to Jamf CDP.

jamfcpr 1.0.2 with same configuration and user account uploads successfully.

**Comment by BIG-RAT** [comment]
What version of Jamf Pro is the destination server.  Anything interesting in the log (~/Library/Logs/jamfcpr/...)?

**Comment by pete-c-jll** [comment]
From 10.15.7 device inside the JLL network.

From: Leslie Helou ***@***.***>
Date: Friday, May 21, 2021 at 6:34 AM
To: BIG-RAT/jamfcpr ***@***.***>
Cc: Curtner, Pete ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [BIG-RAT/jamfcpr] Unable to retrieve upload information for destination server (#6)

What version of Jamf Pro is the destination server. Anything interesting in the log (~/Library/Logs/jamfcpr/...)?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBIG-RAT%2Fjamfcpr%2Fissues%2F6%23issuecomment-845887343&data=04%7C01%7Cpete.curtner%40am.jll.com%7C08d53afb1b904bea7b0508d91c4c5357%7Cbfef2b06d2564f8ebd038d3687987063%7C0%7C0%7C637571936413237875%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6CrZRmEss1P2OH6efW70wCr5BMjJrzF3cSnST3%2BGgQQ%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATS6VUL4XPA7Q6VS3CBOT6LTOZAKLANCNFSM45HXPIYQ&data=04%7C01%7Cpete.curtner%40am.jll.com%7C08d53afb1b904bea7b0508d91c4c5357%7Cbfef2b06d2564f8ebd038d3687987063%7C0%7C0%7C637571936413247829%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=q9lPVaPXJjUIpas31c5lmwv870lMG5oqjClZ6nI5VjQ%3D&reserved=0>.


One of the 2021 World’s Most Ethical Companies® <http://www.jll.com/WME2021>

Jones Lang LaSalle

For more information about how JLL processes your personal data, please click here <http://www.jll.com/privacy-statement>.

This email is for the use of the intended recipient(s) only. If you have received this email in error, please notify the sender immediately and then delete it. If you are not the intended recipient, you must not keep, use, disclose, copy or distribute this email without the author's prior permission. We have taken precautions to minimize the risk of transmitting software viruses, but we advise you to carry out your own virus checks on any attachment to this message. We cannot accept liability for any loss or damage caused by software viruses. The information contained in this communication may be confidential and may be subject to the attorney-client privilege. If you are the intended recipient and you do not wish to receive similar electronic messages from us in the future then please respond to the sender to this effect.
