### ISSUE TITLE
Deletion of Source Files

### ISSUE THREAD

**Issue by jeolsen** [BIG-RAT/jamfcpr#8]
Twice now i've noticed that if CPR stops responding (no updates in the UI or log file over 30 minutes) and is force quit, the source content can be lost.  Meaning actually deleted from the source/principal share.

Source is on-prem jamf pro 10.28.0 with SMB share on Windows Server 2012 R2. Destination is Jamf Cloud Distribution Point

**Comment by BIG-RAT** [comment]
Any chance you can provide the logs from when this happened?  I'll start digging in the mean time.
